name: apidash

packages:
  - packages/**

scripts:
  analyze:
    run: dart run melos exec -- "flutter analyze"
    description: Analyze all packages

  clean:
    run: dart run melos exec -- "flutter clean"
    description: Clean all packages

  build-gen:
    run: dart run melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run build generator for all packages

  test:
    run: dart run melos exec --dir-exists=test -- "flutter test --coverage"
    description: Run tests for all packages

  pub-get:
    run: dart run melos exec -- "flutter pub get"
    description: Run pub get for all packages
